//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Single ThrustUp
        {
            get
            {
                return SteamVR_Actions.default_ThrustUp;
            }
        }
        
        public virtual SteamVR_Action_Single ThrustDown
        {
            get
            {
                return SteamVR_Actions.default_ThrustDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean RollMode
        {
            get
            {
                return SteamVR_Actions.default_RollMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.default_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.default_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Back
        {
            get
            {
                return SteamVR_Actions.default_Back;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.default_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Map
        {
            get
            {
                return SteamVR_Actions.default_Map;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Look
        {
            get
            {
                return SteamVR_Actions.default_Look;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftHand
        {
            get
            {
                return SteamVR_Actions.default_LeftHand;
            }
        }
        
        public virtual SteamVR_Action_Pose RightHand
        {
            get
            {
                return SteamVR_Actions.default_RightHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean Autopilot
        {
            get
            {
                return SteamVR_Actions.default_Autopilot;
            }
        }
        
        public virtual SteamVR_Action_Boolean Recenter
        {
            get
            {
                return SteamVR_Actions.default_Recenter;
            }
        }
        
        public virtual SteamVR_Action_Boolean UISelect
        {
            get
            {
                return SteamVR_Actions.default_UISelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean Stationary_Use
        {
            get
            {
                return SteamVR_Actions.default_Stationary_Use;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Stationary_DPAD
        {
            get
            {
                return SteamVR_Actions.default_Stationary_DPAD;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
