// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR {
    using System;
    using UnityEngine;


    public class SteamVR_Input_ActionSet_inverted: Valve.VR.SteamVR_ActionSet {

        public virtual SteamVR_Action_Boolean Grip {
            get {
                return SteamVR_Actions.inverted_Grip;
            }
        }

        public virtual SteamVR_Action_Single ThrustUp {
            get {
                return SteamVR_Actions.inverted_ThrustUp;
            }
        }

        public virtual SteamVR_Action_Single ThrustDown {
            get {
                return SteamVR_Actions.inverted_ThrustDown;
            }
        }

        public virtual SteamVR_Action_Boolean RollMode {
            get {
                return SteamVR_Actions.inverted_RoolMode;
            }
        }

        public virtual SteamVR_Action_Boolean Interact {
            get {
                return SteamVR_Actions.inverted_Interact;
            }
        }

        public virtual SteamVR_Action_Boolean Jump {
            get {
                return SteamVR_Actions.inverted_Jump;
            }
        }

        public virtual SteamVR_Action_Boolean Back {
            get {
                return SteamVR_Actions.inverted_Back;
            }
        }

        public virtual SteamVR_Action_Boolean Menu {
            get {
                return SteamVR_Actions.inverted_Menu;
            }
        }

        public virtual SteamVR_Action_Boolean Map {
            get {
                return SteamVR_Actions.inverted_Map;
            }
        }

        public virtual SteamVR_Action_Vector2 Look {
            get {
                return SteamVR_Actions.inverted_Look;
            }
        }

        public virtual SteamVR_Action_Vector2 Move {
            get {
                return SteamVR_Actions.inverted_Move;
            }
        }

        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.inverted_Squeeze;
            }
        }

        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.inverted_GrabPinch;
            }
        }
    }
}
