// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_mixedreality : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose ExternalCamera
        {
            get
            {
                return SteamVR_Actions.mixedreality_ExternalCamera;
            }
        }
    }
}
