// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR {
    using System;
    using UnityEngine;


    public class SteamVR_Input_ActionSet_tools: Valve.VR.SteamVR_ActionSet {

        public virtual SteamVR_Action_Vector2 DPad {
            get {
                return SteamVR_Actions.tools_DPad;
            }
        }

        public virtual SteamVR_Action_Boolean Use {
            get {
                return SteamVR_Actions.tools_Use;
            }
        }
    }
}
