// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Single ThrottleUp
        {
            get
            {
                return SteamVR_Actions.default_ThrottleUp;
            }
        }
        
        public virtual SteamVR_Action_Single ThrottleDown
        {
            get
            {
                return SteamVR_Actions.default_ThrottleDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryAction
        {
            get
            {
                return SteamVR_Actions.default_SecondaryAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimaryAction
        {
            get
            {
                return SteamVR_Actions.default_PrimaryAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.default_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Back
        {
            get
            {
                return SteamVR_Actions.default_Back;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.default_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Map
        {
            get
            {
                return SteamVR_Actions.default_Map;
            }
        }
        
        public virtual SteamVR_Action_Boolean LockOn
        {
            get
            {
                return SteamVR_Actions.default_LockOn;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Look
        {
            get
            {
                return SteamVR_Actions.default_Look;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftHand
        {
            get
            {
                return SteamVR_Actions.default_LeftHand;
            }
        }
        
        public virtual SteamVR_Action_Pose RightHand
        {
            get
            {
                return SteamVR_Actions.default_RightHand;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
