// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean X
        {
            get
            {
                return SteamVR_Actions.default_X;
            }
        }
        
        public virtual SteamVR_Action_Boolean A
        {
            get
            {
                return SteamVR_Actions.default_A;
            }
        }
        
        public virtual SteamVR_Action_Boolean Y
        {
            get
            {
                return SteamVR_Actions.default_Y;
            }
        }
        
        public virtual SteamVR_Action_Boolean B
        {
            get
            {
                return SteamVR_Actions.default_B;
            }
        }
        
        public virtual SteamVR_Action_Boolean RB
        {
            get
            {
                return SteamVR_Actions.default_RB;
            }
        }
        
        public virtual SteamVR_Action_Boolean LB
        {
            get
            {
                return SteamVR_Actions.default_LB;
            }
        }
        
        public virtual SteamVR_Action_Single RT
        {
            get
            {
                return SteamVR_Actions.default_RT;
            }
        }
        
        public virtual SteamVR_Action_Single LT
        {
            get
            {
                return SteamVR_Actions.default_LT;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RStick
        {
            get
            {
                return SteamVR_Actions.default_RStick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LStick
        {
            get
            {
                return SteamVR_Actions.default_LStick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Start
        {
            get
            {
                return SteamVR_Actions.default_Start;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.default_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean DUp
        {
            get
            {
                return SteamVR_Actions.default_DUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean DDown
        {
            get
            {
                return SteamVR_Actions.default_DDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean DLeft
        {
            get
            {
                return SteamVR_Actions.default_DLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean DRight
        {
            get
            {
                return SteamVR_Actions.default_DRight;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
