// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        private static SteamVR_Input_ActionSet_tools p__tools;

        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy <SteamVR_Input_ActionSet_default>();
            }
        }

        public static SteamVR_Input_ActionSet_tools _tools
        {
            get
            {
                return SteamVR_Actions.p__tools.GetCopy<SteamVR_Input_ActionSet_tools>();
            }
        }

        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p__tools = ((SteamVR_Input_ActionSet_tools)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_tools>("/actions/tools")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[]
            {
                    SteamVR_Actions._default,
                    SteamVR_Actions._tools
            };
        }
    }
}
